<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class PegawaiFactory extends Factory
{
    public function definition(): array
    {
        return [
            'nip_baru' => fake()->numerify('####################'),
            'nip_lama' => fake()->optional()->numerify('##########'),
            'nama' => fake()->name(),
            'gelar_depan' => fake()->optional()->word(),
            'gelar_blk' => fake()->optional()->word(),
            'tempat_lahir_nama' => fake()->city(),
            'jenis_kelamin' => fake()->randomElement(['L', 'P']),
            'gol_darah' => fake()->optional()->randomElement(['A', 'B', 'AB', 'O']),
            'agama_nama' => fake()->randomElement(['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu']),
            'jenis_kawin_nama' => fake()->randomElement(['Belum Kawin', 'Kawin', 'Cerai Hidup', 'Cerai Mati']),
            'nik' => fake()->optional()->numerify('##################'),
            'nomor_hp' => fake()->phoneNumber(),
            'email' => fake()->optional()->safeEmail(),
            'email_gov' => fake()->optional()->safeEmail(),
            'alamat' => fake()->optional()->address(),
            'foto' => null,
            'tgl_lahir' => fake()->date(),
            'usia' => fake()->numberBetween(20, 60),
            'npwp_nomor' => fake()->optional()->numerify('###################'),
            'bpjs' => fake()->optional()->numerify('##################'),
            'kartu_pegawai' => fake()->optional()->numerify('##########'),
            'nomor_sk_cpns' => fake()->optional()->numerify('##########'),
            'tgl_sk_cpns' => fake()->optional()->date(),
            'tmt_cpns' => fake()->optional()->date(),
            'nomor_sk_pns' => fake()->optional()->numerify('##########'),
            'tgl_sk_pns' => fake()->optional()->date(),
            'tmt_pns' => fake()->optional()->date(),
            'no_sk_dpk_penugasan_kontrak' => fake()->optional()->numerify('##########'),
            'tgl_sk_dpk_penugasan_kontrak' => fake()->optional()->date(),
            'keterangan' => fake()->optional()->sentence(),
            'tgl_kgb_terakhir' => fake()->optional()->date(),
            'keterangan_status' => fake()->optional()->word(),
            'gol_awal_nama' => fake()->optional()->randomElement(['I/a', 'I/b', 'I/c', 'I/d', 'II/a', 'II/b', 'II/c', 'II/d', 'III/a', 'III/b', 'III/c', 'III/d', 'IV/a', 'IV/b', 'IV/c', 'IV/e']),
            'gol_nama' => fake()->randomElement(['I/a', 'I/b', 'I/c', 'I/d', 'II/a', 'II/b', 'II/c', 'II/d', 'III/a', 'III/b', 'III/c', 'III/d', 'IV/a', 'IV/b', 'IV/c', 'IV/e']),
            'tmt_golongan' => fake()->date(),
            'mkgol' => fake()->numberBetween(0, 30),
            'jenis_jabatan_nama' => fake()->randomElement(['Jabatan Fungsional', 'Jabatan Struktural', 'Jabatan Pimpinan Tinggi', 'Jabatan Administrasi']),
            'jabatan_nama' => fake()->jobTitle(),
            'tmt_jabatan' => fake()->date(),
            'jabatan_non_definitif' => fake()->optional()->jobTitle(),
            'jabatan_non_definitif_1' => fake()->optional()->jobTitle(),
            'mkjab' => fake()->numberBetween(0, 20),
            'jumlah' => fake()->optional()->numberBetween(1, 100),
            'kelas' => fake()->optional()->word(),
            'kelas_jabatan' => fake()->optional()->numerify('##'),
            'kelompok_jabatan' => fake()->optional()->numerify('#'),
            'nm_kelompok_jabatan' => fake()->optional()->word(),
            'nama_kelompok_jabatan' => fake()->optional()->word(),
            'pangkat' => fake()->randomElement(['Pengatur Muda', 'Pengatur', 'Pengatur Tingkat I', 'Penata Muda', 'Penata', 'Penata Tingkat I', 'Pembina', 'Pembina Tingkat I', 'Pembina Utama Muda', 'Pembina Utama Madya', 'Pembina Utama']),
            'proyeksi_jf' => fake()->optional()->word(),
            'tingkat_pendidikan_nama' => fake()->randomElement(['SD', 'SMP', 'SMA', 'D3', 'S1', 'S2', 'S3']),
            'pendidikan_nama' => fake()->word(),
            'tahun_lulus' => fake()->year(),
            'riwayat_diklatpim' => fake()->optional()->sentence(),
            'satuan_kerja' => fake()->optional()->word(),
            'unit_kerja' => fake()->optional()->word(),
            'unit_organisasi' => fake()->optional()->word(),
            'unor_nama' => fake()->optional()->word(),
            'instansi_induk_nama' => fake()->optional()->word(),
            'eselon' => fake()->optional()->randomElement(['Eselon I', 'Eselon II', 'Eselon III', 'Eselon IV', 'Non Eselon']),
            'divisi' => fake()->optional()->word(),
            'ukm' => fake()->optional()->word(),
            'range_umur' => fake()->optional()->word(),
            'provinsi' => fake()->state(),
            'kab_kota' => fake()->city(),
            'jenis_pegawai' => fake()->randomElement(['PNS', 'PPPK', 'Honorer']),
            'status_kepegwaian' => fake()->randomElement(['Aktif', 'Pensiun', 'Mutasi', 'Meninggal']),
        ];
    }
}
